### ISSUE TITLE
Stuck on Login

### ISSUE THREAD

**Issue by skehr** [DNguyen17/StableStudy#33]
When you click on Login, there is no way to return to the landing/home page. This is an issue for someone that accidentally clicks on Login instead of Register because they wouldn't be able to go back and click on register even after clicking the "back" button on my browser.  Making it so if someone clicked the blurred background of the landing/home page it would return them to it is a potential solution.

Frequency: every time

Tester: Shelby Kehr skehr@smu.edu
Browser: Chrome

**Comment by DNguyen17** [comment]
currently pressing ESC works.. will add more options
